### ISSUE TITLE
Installing GUI version is broken on Ubuntu 22.04 

### ISSUE THREAD

**Issue by q4a** [nicoboss/nsz#112]
Here is log:
```
~/git/nsz$ python3 -m pip install --upgrade "Cython>=0.24,<=0.29.14,!=0.27,!=0.27.2"
Defaulting to user installation because normal site-packages is not writeable
Collecting Cython!=0.27,!=0.27.2,<=0.29.14,>=0.24
  Downloading Cython-0.29.14.tar.gz (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Unable to find pgen, not compiling formal grammar.
      running egg_info
      creating /tmp/pip-pip-egg-info-s8ni94ez/Cython.egg-info
      writing /tmp/pip-pip-egg-info-s8ni94ez/Cython.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-s8ni94ez/Cython.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-s8ni94ez/Cython.egg-info/entry_points.txt
      writing top-level names to /tmp/pip-pip-egg-info-s8ni94ez/Cython.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-s8ni94ez/Cython.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-thqiq43a/cython_a88e8ba1c2534227b8c78d1886a70db6/setup.py", line 228, in <module>
          setup(
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
          mm.run()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 560, in run
          self.add_defaults()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 306, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/home/q/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-thqiq43a/cython_a88e8ba1c2534227b8c78d1886a70db6/Cython/Distutils/build_ext.py", line 20, in finalize_options
          self.distribution.ext_modules[:] = cythonize(
        File "/tmp/pip-install-thqiq43a/cython_a88e8ba1c2534227b8c78d1886a70db6/Cython/Build/Dependencies.py", line 959, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-install-thqiq43a/cython_a88e8ba1c2534227b8c78d1886a70db6/Cython/Build/Dependencies.py", line 752, in create_extension_list
          elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      AttributeError: module 'collections' has no attribute 'Iterable'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Here is some system info:
```
~/git/nsz$ python3 --version
Python 3.10.4
~/git/nsz$ pip --version
pip 22.2.2 from /home/q/.local/lib/python3.10/site-packages/pip (python 3.10)
~/git/nsz$ uname -a
Linux i5-3450 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
~/git/nsz$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

**Comment by Masamune3210** [comment]
This isnt a issue with nsz, this is a issue with one of the dependencies not installing correctly

**Comment by q4a** [comment]
Ok. I understand that and used command line version. This "issue" is for people that have same problem: this is known problem and I don't know solution.

**Comment by nakezzz** [comment]
same problem

**Comment by nicoboss** [comment]
I just tested the latest commit of nsz on Ubuntu 22.04 and it worked perfectly fine. It was actually way easier to install thanm it used to be. Just pip3 install latest pycryptodome, zstandard, enlighten and kivy and it will just work! Do not use "install_linux.sh" anymore as kivy finaly fixed it's Linux issues.

![nsz_Ubuntu_22 04](https://user-images.githubusercontent.com/623410/188286514-60827eb5-0166-483c-bdde-240691c1bb97.PNG)

**Comment by nicoboss** [comment]
I just updated nsz to now work on Ubuntu 22.04 and Linux in general with GUI just by executing `pip3 install -r requirements-gui.txt` followed by `python3 nsz.py`

![nsz_Ubuntu_22 04_fixed](https://user-images.githubusercontent.com/623410/188288537-e6bd0604-d5bc-4866-981c-070b579c671f.PNG)
