### ISSUE TITLE
Corrupted XCZ when compressing combined XCI

### ISSUE THREAD

**Issue by DarkCTO** [nicoboss/nsz#145]
> source /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/venv/bin/activate && ls -S *.nsp | sed "s|^|$PWD/|" > multi.txt && python /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/squirrel.py -o "$PWD" -dmul "file" -t xci -tfile "$PWD/multi.txt" && deactivate

```
Calculating final content:
Filename: file.xci
        - Writing XCI header...                                                                        
        - Writing XCI game info...                                                                     
        - Generating padding...                                                                        
        - Writing XCI certificate...                                                                   
        - Writing ROOT HFS0 header...                                                                  
        - Writing UPDATE partition header...                                                           
          Calculated multiplier: 1                                                                     
        - Writing NORMAL partition header...                                                           
          Calculated multiplier: 1                                                                     
        - Writing SECURE partition header...                                                           
          Calculated multiplier: 2                                                                     
                                                                                                       
        rightsId =      b'010038b0084ea0000000000000000004'                                            
        titleKeyDec =   b'ca987162e9a529d678267c2d1e75b3d2'                                            
        masterKeyRev =  0x4                                                                            
                                                                                                       
        * Appending: 629c67ffd53b3648514dc1adb25712d7.nca                                              
        * Appending: be95d4aed8f5afd652744760fd1c16fd.nca                                              
        * Appending: 4ad576684d09767e06ca1025d9cb4330.nca                                              
        * Appending: 65697e16736246663ee10e398ab1e179.cnmt.nca                                         
                                                                                                       
        rightsId =      b'010038b0084ea8000000000000000004'                                            
        titleKeyDec =   b'6f673b9b622023123ab35befea19a6d4'                                            
        masterKeyRev =  0x4                                                                            
                                                                                                       
        * Appending: 9a25fa898d854b4ef4ce2354de08e3da.nca                                              
        * Appending: ae3f1164f78e840d56451b82637e4736.nca                                              
        * Appending: 68d376e020e1724fdc417f7fe7bb4a33.nca                                              
        * Appending: 45d21ff2f7488707cda3d0b43d835524.cnmt.nca        
```                                 

`source /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/venv/bin/activate && python /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz.py --quick-verify -p -w -C file.xci -o "$PWD" && deactivate`

```
             NSZ v4.5   ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

Block compressing (level 18) /home/kudy/Downloads/unknownFileName/file.xci -> /home/kudy/Downloads/unknownFileName/file.xcz
[ADDING]     secure 0 bytes to NSP
[ADDING]     629c67ffd53b3648514dc1adb25712d7.ncz 409960448 bytes to NSP

compressed 22% 409960448 -> 90762700  - 629c67ffd53b3648514dc1adb25712d7.nca
[ADDING]     be95d4aed8f5afd652744760fd1c16fd.nca 790528 bytes to NSP
[ADDING]     4ad576684d09767e06ca1025d9cb4330.nca 165376 bytes to NSP
[ADDING]     65697e16736246663ee10e398ab1e179.cnmt.nca 3584 bytes to NSP
[ADDING]     9a25fa898d854b4ef4ce2354de08e3da.ncz 22385664 bytes to NSP
compressed 67% 22385664 -> 15036730  - 9a25fa898d854b4ef4ce2354de08e3da.nca
[ADDING]     ae3f1164f78e840d56451b82637e4736.nca 790528 bytes to NSP
[ADDING]     68d376e020e1724fdc417f7fe7bb4a33.nca 165376 bytes to NSP
[ADDING]     45d21ff2f7488707cda3d0b43d835524.cnmt.nca 4096 bytes to NSP
[VERIFY NSZ] /home/kudy/Downloads/unknownFileName/file.xcz
[NCZBLOCK]   Using Block decompresion

[CORRUPTED]  629c67ffd53b3648514dc1adb25712d7.ncz
Error while compressing file: /home/kudy/Downloads/unknownFileName/file.xci
Traceback (most recent call last):
  File "/run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz/__init__.py", line 174, in main
    compress(filePath, outFolder, args, work, amountOfTastkQueued)
  File "/run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz/__init__.py", line 59, in compress
    verify(outFile, args.remove_padding, True, args.keep_delta, None if args.quick_verify else filePath)
  File "/run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz/__init__.py", line 70, in verify
    NszVerify(filePath, removePadding, raiseVerificationException, raisePfs0Exception, originalFilePath, statusReportInfo, pleaseNoPrint)
  File "/run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz/NszDecompressor.py", line 48, in verify
    __decompressXcz(filePath, None, removePadding, False, raiseVerificationException, raisePfs0Exception, originalFilePath, statusReportInfo, pleaseNoPrint)
  File "/run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz/NszDecompressor.py", line 247, in __decompressXcz
    __decompressContainer(secureIn, None, fileHashes, write, raiseVerificationException, raisePfs0Exception, statusReportInfo, pleaseNoPrint)
  File "/run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz/NszDecompressor.py", line 87, in __decompressContainer
    raise VerificationException("Verification detected hash mismatch")
nsz.NszDecompressor.VerificationException: Verification detected hash mismatch

Done!szDecompressor.VerificationException: Verification detected hash mismatchr.py", line 87, in __decompressContainerortInfo, pleaseNoPrint) pleaseNoPrint)███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 390/390 MiB [00:01<00:00, 462.19 MiB/s]
```

**Comment by seiya-git** [comment]
NSC_Builder doesn't support zstd block compression, its not nsz bug

**Comment by DarkCTO** [comment]
Only NSC combined files can at least have some progress with nsz.
No other merging tools I have tried give files that can be used with nsz, nsz will not even attempt it.

**Comment by nicoboss** [comment]
Why don't you just use solid compression if you want your XCZ files to be compatible with NSC_Builder and other tools not supporting block compression? To do so use the `--solid` command line argument or if you are using the NSZ GUI under "Settings" enable the "[XCZ] Use Solid Compression" option. I would love if every tool could support all the features of the NSZ/XCZ file format but in the end, those are all spare time projects and many developers don’t have time to make their tools perfect.

**Comment by nicoboss** [comment]
What do you mean with merging xci files? You mean that if you dump a very large game using nxdumptool to a fat32 partition it results in a folder contain multiple files each containing a part of your dumped game and you want to make it a single file again? Can’t you just concatenate them together using something like `cat game.xci/00 game.xci/01 game.xci/02 > game.xci`. Or what do you mean?

**Comment by DarkCTO** [comment]
Maybe I'm missing something here, but your README.md said solid is the default... 
```
  -S, --solid           Use solid compression option. Slightly higher
                        compression ratio but won't allow for random read
                        access. File compressed this way will never be
                        mountable (have to be installed or decompressed first
                        to run). This is the default option for NSZ.
```
Thanks for the suggestion, seems like default is block compression. I'll try it out.
As long as something works, I don't mind each tool being not perfect.

I can't merge all updates/dlcs into one xci and compress the merged XCI with nsz... that's frustrating.
SAK outputs doesn't work because they use hactool.
But NSC_Builder/Squirrel.Py/Nut are using the toolchain that nsz uses to encrypt/decrypt.

nsz could simply allow to compress a folder with subfolders and it will be golden.
NSC_Builder just create 3 folder: normal, secure and update
And copy all NCAs files from all base+update+dlc NSPs and put into the secure folder.

**Comment by nicoboss** [comment]
Block compression is the default for XCZ (compressed XCI) while solid compression is the default for NSZ (compressed NSZ). This is because users compressing XCI files expect to be able to play them without decompressing them while NSP files are known to be required to be installed first before they can be played. I choose the default values so they best match user expectations.

I stated under `--block` `This is the default option for XCZ` while I stated under `--solid` `This is the default option for XCZ`. You are working with XCZ and not NSZ files why the default is block compression so specifying `--solid` is required if you want to use solid compression instead.

I now see what you want. Maybe I will implement this in the future but for NSZ v5.0 I already focus on making block compressed NSZ/XCZ files mountable so they can be used for emulators without decompressing them first but after that I could work on this.

Please let me know if using `--solid` fixes your issue for now.

**Comment by DarkCTO** [comment]
Same issue with `--solid` 

`source /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/venv/bin/activate && python /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz.py \#Breakforcist\ Battle\[010038B0084EA800\]\[US\]\[v65536\].xci -C --solid -o ~/`

```
             NSZ v4.5   ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

Solid compressing (level 18) /run/media/kudy/KG/switch/#Breakforcist Battle[010038B0084EA800][US][v6553
6].xci -> /home/kudy/#Breakforcist Battle[010038B0084EA800][US][v65536].xcz
[ADDING]     secure 0 bytes to NSP
[ADDING]     629c67ffd53b3648514dc1adb25712d7.ncz 409960448 bytes to NSP
Compressed 21.894366746325733% 409960448 -> 89758244  - 629c67ffd53b3648514dc1adb25712d7.nca
[ADDING]     be95d4aed8f5afd652744760fd1c16fd.nca 790528 bytes to NSP
[ADDING]     4ad576684d09767e06ca1025d9cb4330.nca 165376 bytes to NSP
[ADDING]     65697e16736246663ee10e398ab1e179.cnmt.nca 3584 bytes to NSP
[ADDING]     9a25fa898d854b4ef4ce2354de08e3da.ncz 22385664 bytes to NSP
Compressed 66.09213378705229% 22385664 -> 14795163  - 9a25fa898d854b4ef4ce2354de08e3da.nca
[ADDING]     ae3f1164f78e840d56451b82637e4736.nca 790528 bytes to NSP
[ADDING]     68d376e020e1724fdc417f7fe7bb4a33.nca 165376 bytes to NSP
[ADDING]     45d21ff2f7488707cda3d0b43d835524.cnmt.nca 4096 bytes to NSP

Compressing 100%|████████████████████████████████████████████████| 21/21 MiB [00:14<00:00, 1.55 MiB/s]

Done!

```

`source /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/venv/bin/activate && python /run/media/kudy/DATA/Software/NSC_Builder/py/ztools/nsz.py \#Breakforcist\ Battle\[010038B0084EA800\]\[US\]\[v65536\].xcz -D`

```
             NSZ v4.5   ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

Decompressing /home/kudy/#Breakforcist Battle[010038B0084EA800][US][v65536].xcz -> /home/kudy/#Breakforcist Battle[010038B0084EA800][US][v65536].xci
[ADDING]     secure 0 bytes to NSP
[ADDING]     629c67ffd53b3648514dc1adb25712d7.nca 89758244 bytes to NSP

[CORRUPTED]  629c67ffd53b3648514dc1adb25712d7.ncz
[ADDING]     be95d4aed8f5afd652744760fd1c16fd.nca 790528 byt
es to NSP
[VERIFIED]   be95d4aed8f5afd652744760fd1c16fd.nca
[ADDING]     4ad576684d09767e06ca1025d9cb4330.nca 165376 byt
es to NSP
[VERIFIED]   4ad576684d09767e06ca1025d9cb4330.nca
[ADDING]     65697e16736246663ee10e398ab1e179.cnmt.nca 3584 
bytes to NSP
[ADDING]     9a25fa898d854b4ef4ce2354de08e3da.nca 14795163 b
ytes to NSP

[CORRUPTED]  9a25fa898d854b4ef4ce2354de08e3da.ncz
[ADDING]     ae3f1164f78e840d56451b82637e4736.nca 790528 byt
es to NSP
[VERIFIED]   ae3f1164f78e840d56451b82637e4736.nca
[ADDING]     68d376e020e1724fdc417f7fe7bb4a33.nca 165376 byt
es to NSP
[VERIFIED]   68d376e020e1724fdc417f7fe7bb4a33.nca
[ADDING]     45d21ff2f7488707cda3d0b43d835524.cnmt.nca 4096 
bytes to NSP

Done!


Decompress 100%|█████| 21/21 MiB [00:00<00:00, 278.14 MiB/s]
```

**Comment by seiya-git** [comment]
Why you use nsz in nscb? Those Fs and nut inside nscb not compatible with nsz

**Comment by DarkCTO** [comment]
Finally I got it, turned out squirrel.py has their own nsz compression.

Compression:

`ls -S *.nsp | sed "s|^|$PWD/|" > multi.txt && python squirrel.py -o "$PWD" -dmul "file" -t xci -tfile "$PWD/multi.txt" && python squirrel.py -cpr "$PWD/file.xci" && deactivate`

Decompression

`python squirrel.py -dcpr "$PWD/file.xcz" -o "$PWD" `

**Comment by DarkCTO** [comment]
NOTE: you need to change squirrel.py line 2827

Change 

```
					for inpt in args.decompress:
						filepath=inpt
						break
```

To `filepath=args.decompress`
