### ISSUE TITLE
Nuitka standalone executable builds crash on block compression

### ISSUE THREAD

**Issue by nicoboss** [nicoboss/nsz#26]
Nuitka builds crash on block compresson:
```
python.exe: error: unrecognized arguments: --multiprocessing-fork
nut exception: 2
Error when compressing file: C:\Users\Administrator\Documents\NSZ\nsz\nsz.dist\SNES_Online_01008D300C50C000_v0_original.nsp
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\NSZ\nsz\nsz.dist\nsz\BlockCompressor.py", line 85, in blockCompress
  File "C:\Users\Administrator\Documents\NSZ\nsz\nsz.dist\multiprocessing\context.py", line 56, in Manager
  File "C:\Users\Administrator\Documents\NSZ\nsz\nsz.dist\multiprocessing\managers.py", line 567, in start
  File "C:\Users\Administrator\Documents\NSZ\nsz\nsz.dist\multiprocessing\connection.py", line 250, in recv
  File "C:\Users\Administrator\Documents\NSZ\nsz\nsz.dist\multiprocessing\connection.py", line 306, in _recv_bytes
```

**Comment by nicoboss** [comment]
Well neverminded I didn't read the Nuitka warning - after reading it I know what to do:
```
PS C:\Users\Administrator\Documents\NSZ\nsz> nuitka nsz.py --standalone
Nuitka:WARNING:Use '--plugin-enable=multiprocessing' for: Multiprocessing workarounds for compiled code on Windows.
```
Please use `nuitka nsz.py --standalone --plugin-enable=multiprocessing` and things will work.
