### ISSUE TITLE
Error when using --rm-old-version

### ISSUE THREAD

**Issue by AustinHasten** [nicoboss/nsz#34]
```
Extract TitleID/Version: Donkey Kong Country Tropical Freeze [0100C1F0051B6000][v0].nsp => 0100C1F0051B6000 0
Error when decompressing file: D:\Switch\Games\Donkey Kong Country Tropical Freeze [0100C1F0051B6000]\Donkey Kong Country Tropical Freeze [0100C1F0051B6000][v0].nsz
Traceback (most recent call last):
  File "D:\Switch\nsz-master\nsz\__init__.py", line 156, in main
    if not FileExistingChecks.AllowedToWriteOutfile(filePath, ".nsp", targetDict, args.rm_old_version, args.overwrite, args.parseCnmt):
  File "D:\Switch\nsz-master\nsz\FileExistingChecks.py", line 109, in AllowedToWriteOutfile
    if versionEntry < titleIDEntry:
TypeError: '<' not supported between instances of 'int' and 'dict'
Errors:
Error when processing D:\Switch\Games\Donkey Kong Country Tropical Freeze [0100C1F0051B6000]\Donkey Kong Country Tropical Freeze [0100C1F0051B6000][v0].nsz
Traceback (most recent call last):
  File "D:\Switch\nsz-master\nsz\__init__.py", line 156, in main
    if not FileExistingChecks.AllowedToWriteOutfile(filePath, ".nsp", targetDict, args.rm_old_version, args.overwrite, args.parseCnmt):
  File "D:\Switch\nsz-master\nsz\FileExistingChecks.py", line 109, in AllowedToWriteOutfile
    if versionEntry < titleIDEntry:
TypeError: '<' not supported between instances of 'int' and 'dict'
```

Let me know what other information I can give. Using the master tree from after the 2.1 release was made.

**Comment by nicoboss** [comment]
That part of the enhanced file existing check is completely broken. I was able to recreate your issue and will fix it soon. Funny how every line of code in that part is broken:
```python
if versionEntry < titleIDEntry: #Int and dict obviously can't be compared
	for (fileName, filePath) in filesAtTarget: #This is NOT how to loop over a dictionary
		filesAtTarget.remove(os.path.basename(filePath).name.lower()) #This is NOT how you remove keys from dictionaries
		os.remove(file) # ‘file” isn't defined here also this would this delete EVERY file in the destination
```
This issue occurred because I implemented --rm-old-version with the first version of the enhanced file existing however I later had to change its data structure to cover all edge cases. By doing that I unfortunately missed adopting some code still dependent on the old data structure.

**Comment by nicoboss** [comment]
Thanks to eXhumer this should now be fixed.
