### ISSUE TITLE
File path processing is broken in Solid compressing due to recent changes in Block mode file path fixing @ b3ad221

### ISSUE THREAD

**Issue by skygunner** [nicoboss/nsz#43]
Working fine 2.1.1
Broken at @ b3ad221

Error when compressing file: L:\AASwitch\Some rom . U 测试\a game rom. 测试_[v0].nsp
Traceback (most recent call last):
  File "D:\git\nsz\nsz\__init__.py", line 120, in main
    compress(filePath, outfolder, args)
  File "D:\git\nsz\nsz\__init__.py", line 31, in compress
    outFile = solidCompress(filePath, compressionLevel, outputDir, threadsToUse)
  File "D:\git\nsz\nsz\SolidCompressor.py", line 15, in solidCompress
    if filePath.endswith('.nsp'):
AttributeError: 'WindowsPath' object has no attribute 'endswith'

Summary of errors which occurred while processing files:
Error when processing L:\AASwitch\Some rom . U 测试\a game rom. 测试_[v0].nsp
Traceback (most recent call last):
  File "D:\git\nsz\nsz\__init__.py", line 120, in main
    compress(filePath, outfolder, args)
  File "D:\git\nsz\nsz\__init__.py", line 31, in compress
    outFile = solidCompress(filePath, compressionLevel, outputDir, threadsToUse)
  File "D:\git\nsz\nsz\SolidCompressor.py", line 15, in solidCompress
    if filePath.endswith('.nsp'):
AttributeError: 'WindowsPath' object has no attribute 'endswith'

Done!

**Comment by skygunner** [comment]
Works in block compressing though
