### ISSUE TITLE
"multiprocessing" exceptions

### ISSUE THREAD

**Issue by popy2k14** [nicoboss/nsz#46]
Hey guys.

Tried now to compress my XCI backups and the following pops up a lo in the logs:

`
Traceback (most recent call last):
  File "multiprocessing\connection.py", line 312, in _recv_bytes
BrokenPipeError: [WinError 109] Die Pipe wurde beendet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "nsz\BlockCompressor.py", line 18, in compressBlockTask
  File "<string>", line 2, in get
  File "multiprocessing\managers.py", line 819, in _callmethod
Traceback (most recent call last):
Traceback (most recent call last):
Process Process-6:
  File "multiprocessing\connection.py", line 250, in recv
Traceback (most recent call last):
  File "multiprocessing\connection.py", line 312, in _recv_bytes
  File "multiprocessing\connection.py", line 312, in _recv_bytes
  File "multiprocessing\connection.py", line 321, in _recv_bytes
  File "multiprocessing\connection.py", line 312, in _recv_bytes
BrokenPipeError: [WinError 109] Die Pipe wurde beendet
BrokenPipeError: [WinError 109] Die Pipe wurde beendet
EOFError
BrokenPipeError: [WinError 109] Die Pipe wurde beendet
`
Is this normal/known behaviour?
Because the tool generates XCZ files (which are smaller than the XCI).

**Comment by nicoboss** [comment]
The error you describe was probably fixed in https://github.com/nicoboss/nsz/commit/ba79b343c3b0805dc2597a5f0dfc9384215f5791. XCI compression was broken in prior to nsz v3.1.1 anyways. Please try this on nsz v3.1.1 and reopen this issue if it still occurs on v3.1.1.

**Comment by popy2k14** [comment]
The issue seems to be fixed in 3.1.1, currently compressing/decompressing a few test XCI's.
Sadly, other issues poped up, will raise those issues in several github issues.
