### ISSUE TITLE
Cannot install Witcher 3 converted from xci

### ISSUE THREAD

**Issue by pabermod** [nicoboss/nsz#7]
read returned empty 0x700a828fb
nut exception: read returned empty 0x700a828fb
Traceback (most recent call last):
  File "D:\Descargas\SWITCH\nsz-master\compressor\nsz.py", line 78, in <module>
    nut.compress(filePath, 17 if args.level is None else args.level, args.output)
  File "D:\Descargas\SWITCH\nsz-master\compressor\nut\__init__.py", line 46, in compress
    container.open(filePath, 'rb')
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\Nsp.py", line 205, in open
    super(Nsp, self).open(path or self.path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\Pfs0.py", line 177, in open
    self.files[i].open(None, None)
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\Nca.py", line 215, in open
    self.partition(0x0, 0xC00, self.header, Fs.Type.Crypto.XTS, uhx(Keys.get('header_key')))
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\File.py", line 69, in partition
    n.open(None, None, cryptoType, cryptoKey, cryptoCounter)
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\Nca.py", line 70, in open
    self.signature1 = self.read(0x100)
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\File.py", line 325, in read
    self._buffer = super(BufferedFile, self).read(pageReadSize)
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\File.py", line 86, in read
    return self.f.read(size)
  File "D:\Descargas\SWITCH\nsz-master\compressor\Fs\File.py", line 328, in read
    raise IOError('read returned empty ' + hex(self.offset))
OSError: read returned empty 0x700a828fb

**Comment by blawar** [comment]
Are you sure the dump was complete?  Also, can you try with NSC_Builder?  https://github.com/julesontheroad/NSC_BUILDER

**Comment by pabermod** [comment]
I got an error too with NSC_BUILDER, maybe its not a complete dump

**Comment by pabermod** [comment]
yep, seems like bad nsp

**Comment by L1900L** [comment]
ture
