### ISSUE TITLE
Lots of my NSPs result in this 

### ISSUE THREAD

**Issue by fennectech** [nicoboss/nsz#83]
```
Solid compressing (level 18) /home/fennectech/Backup/NSP/Island Saver by NatWest [0100A2600FCA0800][v65536][UPD].nsp -> /ho
me/fennectech/Backup/NSZ/Island Saver by NatWest [0100A2600FCA0800][v65536][UPD].nsz
Traceback (most recent call last):
  File "/home/fennectech/.local/lib/python3.8/site-packages/nsz/SolidCompressor.py", line 132, in solidCompressNsp
    processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
  File "/home/fennectech/.local/lib/python3.8/site-packages/nsz/SolidCompressor.py", line 29, in processContainer
    offsetFirstSection = sortedFs(nspf)[0].offset
IndexError: list index out of range

```

**Comment by fennectech** [comment]
old prod.keys   Me be a bit dim
