### ISSUE TITLE
Full disk exception error Pfs0.py line 37, File.py line 112, setle.py line 112

### ISSUE THREAD

**Issue by maxmag-soft** [nicoboss/nsz#91]
Hi!
I am sharing with you the Python (and the Pfs0.py lib, File.py lib) exceptions caused by full disk during the compression of a file.

Input and output file are on the same hard disk
16GB of RAM DDR3
Core i7 3770K

`
The above exception was the direct cause of the following exception:
    super(Pfs0Stream, self).write(value, len(value))
SystemError: <class 'super'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\File.py", line 112, in write
    return self.f.write(value)
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\Pfs0.py", line 37, in write
    super(Pfs0Stream, self).write(value, len(value))
SystemError: <class 'super'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
SystemError: <class 'super'> returned a result with an error setle.py", line 112, in write

Compressing 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133/133 MiB [41:44<00:00, 0.05 MiB/s]    super(Pfs0Stream, self).write(value, len(value))
SystemError: <class 'super'> returned a result with an error sets0.py", line 37, in write

The above exception was the direct cause of the following exception:

    super(Pfs0Stream, self).write(value, len(value))

  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\File.py", line 112, in write
Compressing 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139/139 MiB [41:44<00:00, 0.06 MiB/s]SystemError: <class 'super'> returned a result with an error sets0.py", line 37, in write

The above exception was the direct cause of the following exception:

    super(Pfs0Stream, self).write(value, len(value))

  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\File.py", line 112, in write
    return self.f.write(value)
Compressing  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌              |  9216/10521 MiB [41:44<05:55, 3.68 MiB/s]SystemError: <class 'super'> returned a result with an error set

The above exception was the direct cause of the following exception:
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\Pfs0.py", line 37, in write
    super(Pfs0Stream, self).write(value, len(value))

Traceback (most recent call last):
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\File.py", line 112, in write
    return self.f.write(value)

Compressing 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133/133 MiB [41:52<00:00, 0.05 MiB/s]    super(Pfs0Stream, self).write(value, len(value))

  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\Fs\File.py", line 112, in write
Compressing 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139/139 MiB [41:52<00:00, 0.06 MiB/s]SystemError: <class 'super'> returned a result with an error sets0.py", line 37, in write

    processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\SolidCompressor.py", line 97, in processContainer
    compressor.write(buffer)
SystemError: <method 'write' of 'zstd.ZstdCompressionWriter' objects> returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\nsz_v4.0.1_win64_portable\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\nsz_v4.0.1_win64_portable\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\__init__.py", line 36, in solidCompressTask
    outFile = solidCompress(filePath, compressionLevel, outputDir, threadsToUse, statusReport, id, pleaseNoPrint)
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\SolidCompressor.py", line 16, in solidCompress
    return solidCompressNsp(filePath, compressionLevel, outputDir, threads, stusReport, id, pleaseNoPrint)
  File "D:\nsz_v4.0.1_win64_portable\lib\site-packages\nsz\SolidCompressor.py", line 135, in solidCompressNsp
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 485, in __init__
    _seen=_seen)
  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 485, in __init__
    _seen=_seen)
  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 485, in __init__
    _seen=_seen)
  [Previous line repeated 491 more times]
  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 473, in __init__
    _seen.add(id(exc_value))
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\nsz_v4.0.1_win64_portable\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\nsz_v4.0.1_win64_portable\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "D:\nsz_v4.0.1_win64_portable\lib\multiprocessing\process.py", line 313, in _bootstrap
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)

Compressing 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133/133 MiB [41:52<00:00, 0.05 MiB/s]    _seen=_seen)|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139/139 MiB [41:52<00:00, 0.06 MiB/s]

Compressing 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133/133 MiB [1h 20:59<00:00, 0.03 MiB/s]Compressing 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139/139 MiB [1h 20:59<00:00, 0.03 MiB/s]Compressing  88%|████████████████████████████████████████████████████████████████████████████████████████████████████              |  9216/10521 MiB [1h 20:59<11:28, 1.90 MiB/s]Compressing 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 634/634 MiB [1h 20:59<00:00, 0.13 MiB/s]  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 485, in __init__
    _seen=_seen)
  File "D:\nsz_v4.0.1_win64_portable\lib\traceback.py", line 485, in __init__
Compressing 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 634/634 MiB [41:52<00:00, 0.25 MiB/s]    _seen.add(id(exc_value))portable\lib\traceback.py", line 485, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object

Compressing 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133/133 MiB [1h 18:24<00:00, 0.03 MiB/s]Compressing 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139/139 MiB [1h 18:24<00:00, 0.03 MiB/s]Compressing  88%|████████████████████████████████████████████████████████████████████████████████████████████████████              |  9216/10521 MiB [1h 18:24<11:06, 1.96 MiB/s]Compressing 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 634/634 MiB [1h 18:24<00:00, 0.13 MiB/s]
`
</code>
</p>
</details>

**Comment by nicoboss** [comment]
Did this issue occur when you ran out of physical disk space on the drive on which you compressed a game? How to you expect NSZ to behave under these circumstances? First check if there is enough disk space left and only let you compress if at least as much space is left as the size of the uncompressed game? What to do for decompression? Check if there is at least twice the space left as the size of the compressed game?

If this issue was not caused by physically running out of disk space can you please let me know on which game you encountered this issue and try if this issue is fixed on the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release?

**Comment by maxmag-soft** [comment]
- Issue on out of pyshical disk space while compressing
- expected to behave exiting and showing a warning like "operation aborted, no disk space left"
- I wasn't checked free space because I compressed a lot of games and let the device alone, and that behavior showed up.

I will try this behavior on a partitioned disk and will let you know on the 4.1.0 release

Thanks for replying!
